name: mego_food
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_svg: ^2.2.1
  flutter_switch: ^0.3.2
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  intl: ^0.20.2
  pinput: ^5.0.2
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  icon_background_color: "#FFFFFF"
  icon_background_color_dark: "#000000"
  image: assets/images/icon_light.png
  image_dark: assets/images/icon_dark.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#000000"
    image: assets/images/icon_light.png
    image_dark: assets/images/icon_dark.png
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
